const mongoose = require('mongoose');

const billingSchema = new mongoose.Schema({
  invoiceNumber: {
    type: String,
    required: true,
    unique: true,
    uppercase: true
  },
  type: {
    type: String,
    required: [true, 'Bill type is required'],
    enum: ['maintenance', 'parking', 'penalty', 'utility', 'other'],
    default: 'maintenance'
  },
  unit: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Unit',
    required: [true, 'Unit is required']
  },
  billedTo: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'Billed to user is required']
  },
  billingPeriod: {
    from: { type: Date, required: true },
    to: { type: Date, required: true }
  },
  dueDate: {
    type: Date,
    required: [true, 'Due date is required']
  },
  items: [{
    description: { type: String, required: true, trim: true },
    quantity: { type: Number, required: true, min: 0, default: 1 },
    unitPrice: { type: Number, required: true, min: 0 },
    amount: { type: Number, required: true, min: 0 },
    category: { type: String, enum: ['maintenance', 'parking', 'utility', 'penalty', 'other'] }
  }],
  subtotal: {
    type: Number,
    required: [true, 'Subtotal is required'],
    min: 0
  },
  taxes: [{
    name: { type: String, required: true },
    percentage: { type: Number, required: true, min: 0 },
    amount: { type: Number, required: true, min: 0 }
  }],
  totalAmount: {
    type: Number,
    required: [true, 'Total amount is required'],
    min: 0
  },
  status: {
    type: String,
    enum: ['draft', 'sent', 'paid', 'overdue', 'cancelled', 'disputed'],
    default: 'draft'
  },
  payments: [{
    amount: { type: Number, required: true, min: 0 },
    paymentMethod: { type: String, required: true, enum: ['cash', 'cheque', 'bank_transfer', 'online', 'upi', 'card'] },
    transactionId: { type: String, trim: true },
    paymentDate: { type: Date, required: true },
    receivedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    notes: { type: String, maxlength: [200, 'Payment notes cannot exceed 200 characters'] }
  }],
  balanceAmount: {
    type: Number,
    required: true,
    min: 0
  },
  lateFee: {
    type: Number,
    default: 0,
    min: 0
  },
  discount: {
    type: Number,
    default: 0,
    min: 0
  },
  generatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'Generated by user is required']
  },
  sentAt: {
    type: Date
  },
  paidAt: {
    type: Date
  },
  attachments: [{
    filename: { type: String, required: true },
    originalName: { type: String, required: true },
    mimeType: { type: String, required: true },
    size: { type: Number, required: true },
    uploadedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    uploadedAt: { type: Date, default: Date.now }
  }],
  notes: {
    type: String,
    maxlength: [1000, 'Notes cannot exceed 1000 characters']
  },
  autoBilling: {
    enabled: { type: Boolean, default: false },
    nextBillingDate: { type: Date },
    template: { type: mongoose.Schema.Types.ObjectId, ref: 'BillingTemplate' }
  }
}, {
  timestamps: true
});

// Generate invoice number before saving
billingSchema.pre('save', async function(next) {
  if (this.isNew && !this.invoiceNumber) {
    const year = new Date().getFullYear();
    const month = String(new Date().getMonth() + 1).padStart(2, '0');
    const count = await this.constructor.countDocuments({
      createdAt: {
        $gte: new Date(year, new Date().getMonth(), 1),
        $lt: new Date(year, new Date().getMonth() + 1, 1)
      }
    });
    this.invoiceNumber = `INV${year}${month}${String(count + 1).padStart(4, '0')}`;
  }
  
  // Calculate balance amount
  const totalPaid = this.payments.reduce((sum, payment) => sum + payment.amount, 0);
  this.balanceAmount = this.totalAmount - totalPaid - this.discount;
  
  // Update status based on payments
  if (this.balanceAmount <= 0 && this.status !== 'cancelled') {
    this.status = 'paid';
    this.paidAt = new Date();
  } else if (this.balanceAmount > 0 && new Date() > this.dueDate && this.status === 'sent') {
    this.status = 'overdue';
  }
  
  next();
});

// Virtual for overdue days
billingSchema.virtual('overdueDays').get(function() {
  if (this.status === 'overdue') {
    return Math.ceil((new Date() - this.dueDate) / (1000 * 60 * 60 * 24));
  }
  return 0;
});

// Index for efficient queries
billingSchema.index({ invoiceNumber: 1 });
billingSchema.index({ billedTo: 1, status: 1 });
billingSchema.index({ unit: 1, status: 1 });
billingSchema.index({ dueDate: 1, status: 1 });
billingSchema.index({ billingPeriod: 1 });

module.exports = mongoose.model('Billing', billingSchema);
